STRINGS = {
    "ru": {
        "title": "ЗМЕЙКА",
        "play": "Играть",
        "settings": "Настройки",
        "high_scores": "Рекорды",
        "quit": "Выход",
        "controls": "Управление",
        "language": "Язык",
        "color": "Цвет змейки",
        "resolution": "Разрешение",
        "grid": "Сетка",
        "on": "Вкл",
        "off": "Выкл",
        "fullscreen": "Полноэкранный режим",
        "lives": "Жизни",
        "score": "Счёт",
        "record": "Рекорд",
        "pause": "Пауза",
        "back": "Назад",
        "game_over": "Игра окончена",
        "your_score": "Ваш счёт",
        "press_enter": "Нажмите Enter, чтобы продолжить"
    },
    "en": {
        "title": "SNAKE",
        "play": "Play",
        "settings": "Settings",
        "high_scores": "High Scores",
        "quit": "Quit",
        "controls": "Controls",
        "language": "Language",
        "color": "Snake Color",
        "resolution": "Resolution",
        "grid": "Grid",
        "on": "On",
        "off": "Off",
        "fullscreen": "Fullscreen",
        "lives": "Lives",
        "score": "Score",
        "record": "Record",
        "pause": "Pause",
        "back": "Back",
        "game_over": "Game Over",
        "your_score": "Your Score",
        "press_enter": "Press Enter to continue"
    }
}
